// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqlofwbvxuuvxiycqicc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xbG9md2J2eHV1dnhpeWNxaWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODkzMzksImV4cCI6MjA3Nzc2NTMzOX0.JjgxZZMsY_pD97_wYbyLMJDYq-w8_8-8ubaq2tLjUIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});